---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: Namespace
metadata:
  name: app 
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-storage
  namespace: jenkins
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
spec:
  volumeMode: Filesystem
  storageClassName: jenkins-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi